import type {
  ClicksTypes,
  ClicksMetadata,
  MousedragTypes,
  MousedragMetadata,
  MousedragdropTypes,
  MousedragdropMetadata,
  MousepressTypes,
  MousepressMetadata,
  TouchesTypes,
  TouchesMetadata,
  TouchdragTypes,
  TouchdragMetadata,
  TouchdragdropTypes,
  TouchdragdropMetadata,
  TouchpressTypes,
  TouchpressMetadata,
  KeychordTypes,
  KeychordMetadata,
  KeypressTypes,
  KeypressMetadata,
  KonamiTypes,
  KonamiMetadata,
} from '@baleada/recognizeable-effects'

export type RecognizeableTypeByName = {
  clicks: ClicksTypes,
  mousedrag: MousedragTypes,
  mousedragdrop: MousedragdropTypes,
  mousepress: MousepressTypes,
  touches: TouchesTypes,
  touchdrag: TouchdragTypes,
  touchdragdrop: TouchdragdropTypes,
  touchpress: TouchpressTypes,
  keychord: KeychordTypes,
  keypress: KeypressTypes,
  konami: KonamiTypes,
}

export type RecognizeableMetadataByName = {
  clicks: ClicksMetadata,
  mousedrag: MousedragMetadata,
  mousedragdrop: MousedragdropMetadata,
  mousepress: MousepressMetadata,
  touches: TouchesMetadata,
  touchdrag: TouchdragMetadata,
  touchdragdrop: TouchdragdropMetadata,
  touchpress: TouchpressMetadata,
  keychord: KeychordMetadata,
  keypress: KeypressMetadata,
  konami: KonamiMetadata,
}
